name: waveform_recorder_example
description: "An example of the waveform_recorder package in action."
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  audioplayers: any
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  gap: any
  path: ^1.9.1
  path_provider: ^2.1.5
  waveform_flutter: ^1.2.0
  waveform_recorder:
    path: ../
  web: ^1.1.1

dev_dependencies:
  all_lint_rules_community: ^0.0.41
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
